feat: feature/add-k3d

diff --git a/Taskfile.yaml b/Taskfile.yaml
--- a/Taskfile.yaml
+++ b/Taskfile.yaml
@@ -11,6 +11,8 @@ vars:
   TEST_FILES: tests/helmfiles.yaml
   TEST_DIR: /tmp/helmfiles
   TEST_DEFAULTS: tests/defaults.yaml
+  DEV_CLUSTER: tests/cluster.yaml
+  DEV_CLUSTER_DIR: /tmp/helmfiles/cluster
 
 tasks:
   tasks:
@@ -19,6 +21,134 @@ tasks:
       - |
         task=$(yq e '.tasks | keys' Taskfile.yaml | sed 's/^- //' | gum choose)
         task ${task}
+
+  kind:
+    desc: Create, Start & Configure kind cluster
+    cmds:
+      - rm -rf {{ .DEV_CLUSTER_DIR }}/* && mkdir {{ .DEV_CLUSTER_DIR }} || true
+      - |
+        machineshop render \
+        --source local \
+        --template {{ .DEV_CLUSTER }} \
+        --output file \
+        --values "clusterName={{ .CLUSTER_NAME }}" \
+        --kind multikey \
+        --key kind \
+        --destination {{ .DEV_CLUSTER_DIR }}/{{ .CLUSTER_NAME }}.yaml
+
+      - |
+        if kind get clusters | grep -wq "{{ .CLUSTER_NAME }}"; then
+          echo "Cluster '{{ .CLUSTER_NAME }}' exists (already). Deleting it..."
+          kind delete clusters "{{ .CLUSTER_NAME }}"
+        fi
+
+      - |
+        kind create cluster --config {{ .DEV_CLUSTER_DIR }}/{{ .CLUSTER_NAME }}.yaml --name {{ .CLUSTER_NAME }} --kubeconfig ~/.kube/kind-{{ .CLUSTER_NAME }}
+        kubectl get nodes --kubeconfig ~/.kube/kind-{{ .CLUSTER_NAME }}
+
+      - |
+        machineshop render \
+        --source local \
+        --template {{ .DEV_CLUSTER }} \
+        --output file \
+        --kind multikey \
+        --key kind-infra \
+        --destination {{ .DEV_CLUSTER_DIR }}/{{ .CLUSTER_NAME }}-kind-infra.yaml \
+        --values "source={{ .USER_WORKING_DIR }}"
+
+      - |
+        #!/usr/bin/env bash
+        start_time=$(date +%s)
+        timeout=60  # seconds
+
+        while true; do
+          echo "Running helmfile apply..."
+          helmfile apply -f {{ .DEV_CLUSTER_DIR }}/{{ .CLUSTER_NAME }}-kind-infra.yaml && \
+          echo "Running helmfile sync..." && \
+          helmfile sync -f {{ .DEV_CLUSTER_DIR }}/{{ .CLUSTER_NAME }}-kind-infra.yaml && \
+          { echo "Commands succeeded. Exiting loop."; break; }
+
+          current_time=$(date +%s)
+          elapsed=$(( current_time - start_time ))
+          if [ $elapsed -ge $timeout ]; then
+            echo "Commands are still failing after one minute. Exiting with error."
+            exit 1
+          fi
+          echo "Retrying in 5 seconds..."
+          sleep 5
+        done
+    vars:
+      CLUSTER_NAME: helm-dev
+
+
+
+  k3d:
+    desc: Create, Start & Configure k3d cluster
+    cmds:
+      - |
+        if k3d cluster list --no-headers | grep -wq "{{ .CLUSTER_NAME }}"; then
+          echo "Cluster '{{ .CLUSTER_NAME }}' exists (already). Deleting it..."
+          k3d cluster delete "{{ .CLUSTER_NAME }}"
+        else
+          echo "Cluster '{{ .CLUSTER_NAME }}' does not exist."
+        fi
+      - rm -rf {{ .DEV_CLUSTER_DIR }}/* && mkdir {{ .DEV_CLUSTER_DIR }} || true
+      - |
+        machineshop render \
+        --source local \
+        --template {{ .DEV_CLUSTER }} \
+        --output file \
+        --values "clusterName={{ .CLUSTER_NAME }}" \
+        --kind multikey \
+        --key cluster \
+        --destination {{ .DEV_CLUSTER_DIR }}/{{ .CLUSTER_NAME }}.yaml
+      - k3d cluster create --config {{ .DEV_CLUSTER_DIR }}/{{ .CLUSTER_NAME }}.yaml
+      - k3d kubeconfig get {{ .CLUSTER_NAME }} > ~/.kube/{{ .CLUSTER_NAME }}
+      - |
+        SUBNET=$({{ .CONTAINER_RUNTIME }} network inspect k3d-{{ .CLUSTER_NAME }} | grep -oP '(?<="Subnet": ")[^"]+')
+        BASE_IP=$(echo $SUBNET | cut -d'.' -f1-2)
+        START_IP="${BASE_IP}.255.200"
+        END_IP="${BASE_IP}.255.250"
+        IP_RANGE="${START_IP}-${END_IP}"
+        echo "${IP_RANGE}"
+
+        machineshop render \
+        --source local \
+        --template {{ .DEV_CLUSTER }} \
+        --output file \
+        --kind multikey \
+        --key ip \
+        --destination {{ .DEV_CLUSTER_DIR }}/{{ .CLUSTER_NAME }}-ip.yaml \
+        --values "source={{ .USER_WORKING_DIR }},ipRange=${IP_RANGE}"
+
+        machineshop render \
+        --source local \
+        --template {{ .DEV_CLUSTER }} \
+        --output file \
+        --kind multikey \
+        --key ingress \
+        --destination {{ .DEV_CLUSTER_DIR }}/{{ .CLUSTER_NAME }}-ingress.yaml \
+        --values "source={{ .USER_WORKING_DIR }},ipRange=${IP_RANGE}"
+
+
+      #- helmfile template -f {{ .DEV_CLUSTER_DIR }}/{{ .CLUSTER_NAME }}-ip.yaml
+      - helmfile apply -f {{ .DEV_CLUSTER_DIR }}/{{ .CLUSTER_NAME }}-ip.yaml || true
+      - helmfile sync -f {{ .DEV_CLUSTER_DIR }}/{{ .CLUSTER_NAME }}-ip.yaml || true
+
+      #- helmfile template -f {{ .DEV_CLUSTER_DIR }}/{{ .CLUSTER_NAME }}-ingress.yaml
+      - helmfile apply -f {{ .DEV_CLUSTER_DIR }}/{{ .CLUSTER_NAME }}-ingress.yaml
+
+      # - helmfile template -f {{ .DEV_CLUSTER_DIR }}/{{ .CLUSTER_NAME }}-infra.yaml > {{ .DEV_CLUSTER_DIR }}/rendered.yaml --include-crds
+      # - |
+      #   kubectl --kubeconfig ~/.kube/{{ .CLUSTER_NAME }} create ns metallb-system
+      #   kubectl --kubeconfig ~/.kube/{{ .CLUSTER_NAME }} create ns ingress-nginx
+      #   kubectl --kubeconfig ~/.kube/{{ .CLUSTER_NAME }} create ns cert-manager
+      # - kubectl apply --kubeconfig ~/.kube/{{ .CLUSTER_NAME }} -f {{ .DEV_CLUSTER_DIR }}/rendered.yaml || true
+      # - sleep 15 && kubectl apply --kubeconfig ~/.kube/{{ .CLUSTER_NAME }} -f {{ .DEV_CLUSTER_DIR }}/rendered.yaml || true
+    vars:
+      CONTAINER_RUNTIME: docker
+      CLUSTER_CONFIG_DIR: /tests
+      CLUSTER_NAME: k3d-dev
 
   switch-remote:
     desc: Switch to remote branch
@@ -44,6 +174,7 @@ tasks:
       - rm -rf {{ .TEST_DIR }}/* && mkdir {{ .TEST_DIR }} || true
       - |
         app=$(yq '.template | keys | .[]' tests/helmfiles.yaml | gum choose)
+        folder=$(find {{ .SEARCH_FOLDERS }} -type f -name "${app}.yaml" -exec dirname {} \; | sort -u)
 
         machineshop render \
         --source local \
@@ -52,12 +183,15 @@ tasks:
         --kind multikey \
         --key ${app} \
         --destination {{ .TEST_DIR }}/${app}.yaml \
-        --values "source={{ .USER_WORKING_DIR }}/${app}.yaml"
+        --values "source={{ .USER_WORKING_DIR }}/${folder}/${app}.yaml"
 
         helmfile template -f {{ .TEST_DIR }}/${app}.yaml
         echo "Change to: cd {{ .TEST_DIR }}"
         echo "Apply: helmfile apply -f {{ .TEST_DIR }}/${app}.yaml"
         code {{ .TEST_DIR }}/${app}.yaml
+    vars:
+      SEARCH_FOLDERS: "infra apps database"
+
   tests-create-includes:
     desc: Create test files
     cmds:
