Changed: README.md Taskfile.yaml apps/awx-operator.yaml apps/awx.yaml tests/cluster.yaml tests/releases.yaml

diff --git a/Taskfile.yaml b/Taskfile.yaml
--- a/Taskfile.yaml
+++ b/Taskfile.yaml
@@ -11,87 +11,188 @@ vars:
   TEST_RELEASE_TEMPLATES: tests/releases.yaml
   TEST_DIR: /tmp
   TEST_DEFAULTS: tests/defaults.yaml
-  DEV_CLUSTER: tests/cluster.yaml
+
+  CLUSTER_NAME: helm-dev
+  PATH_KUBE_CONFIG: /home/sthings/.kube/kind-{{ .CLUSTER_NAME }}
+  PATH_CLUSTER_TEMPLATE: tests/cluster.yaml
   DEV_CLUSTER_DIR: /tmp/helmfiles/cluster
+
+
   KIND_CONFIG_PATH: /tmp/kind-config.yaml
-  KIND_INFRA_HELMFILE: /tmp/kind-infra.yaml
+  CLUSTER_INFRA_HELMFILE: /tmp/kind-infra.yaml
   TEST_FILES: tests/releases.yaml
   DATE:
     sh: date +"%Y.%m%d.%H%M"
 
 tasks:
-  tasks:
+  do:
     desc: Select a task to run
     cmds:
       - |
         task=$(yq e '.tasks | keys' Taskfile.yaml | sed 's/^- //' | gum choose)
         task ${task}
 
-  kind:
-    desc: Create, Start & Configure kind cluster
+  test-release:
+    desc: Test a release
     cmds:
-      #- rm -rf {{ .DEV_CLUSTER_DIR }}/* && mkdir {{ .DEV_CLUSTER_DIR }} || true
+      - rm -rf {{ .TEST_DIR }}/* && mkdir {{ .TEST_DIR }} || true
       - |
+        release=$(yq '.template | keys | .[]' {{ .TEST_RELEASE_TEMPLATES }} | gum choose)
+        folder=$(find {{ .SEARCH_FOLDERS }} -type f -name "${release}.yaml" -exec dirname {} \; | sort -u)
+        domain=$(kubectl get nodes -o json | jq -r '.items[] | select(.metadata.labels."ingress-ready" == "true") | .status.addresses[] | select(.type == "InternalIP") | .address').nip.io
+        clusterIssuer=$(kubectl get clusterissuer -o jsonpath='{.items[0].metadata.name}')
+        storageClass=standard
+
         machineshop render \
         --source local \
-        --template {{ .DEV_CLUSTER }} \
+        --template {{ .TEST_RELEASE_TEMPLATES }} \
+        --output file \
+        --kind multikey \
+        --key ${release} \
+        --destination {{ .TEST_DIR }}/${release}.yaml \
+        --values "source={{ .USER_WORKING_DIR }}/${folder}/${release}.yaml, domain=${domain}, clusterIssuer=${clusterIssuer}, storageClass=${storageClass}"
+
+        helmfile template -f {{ .TEST_DIR }}/${release}.yaml
+
+        SELECTED_KUBECONFIG=$(gum choose {{ .ALL_KUBECONFIGS }})
+        echo SWITCHING TO ${SELECTED_KUBECONFIG//\"/}
+        printf "\n\nexport KUBECONFIG={{ .KUBECONFIG_FOLDER }}/${SELECTED_KUBECONFIG//\"/}\n\n"
+
+        export KUBECONFIG={{ .KUBECONFIG_FOLDER }}/${SELECTED_KUBECONFIG//\"/}
+        kubectl get nodes
+
+        code {{ .TEST_DIR }}/${release}.yaml
+
+        gum confirm "Do you want to apply ${release}?" || exit 0
+
+        echo "Apply: helmfile apply -f {{ .TEST_DIR }}/${release}.yaml"
+        helmfile apply -f {{ .TEST_DIR }}/${release}.yaml
+
+        sleep 10 && kubectl get po -A
+
+        gum confirm "Do you want to destroy ${release}?" || exit 0
+        helmfile destroy -f {{ .TEST_DIR }}/${release}.yaml
+        sleep 10 && kubectl get po -A
+    vars:
+      KUBECONFIG_FOLDER: ~/.kube
+      SEARCH_FOLDERS: "infra apps database"
+      ALL_KUBECONFIGS:
+        sh: ls {{ .KUBECONFIG_FOLDER }} | xargs -n1 printf '"%s" '
+
+  execute-base-cluster-setup:
+    desc: Execute base setup on kind cluster
+    vars:
+      RANDOM:
+        sh: |
+          echo $RANDOM % 5555 + 1 | bc
+    env:
+      HELMFILE_CACHE_HOME: /tmp/helmfile/cache/{{ .DATE }}/{{ .RANDOM }}
+      KUBECONFIG: "{{ .PATH_KUBE_CONFIG }}"
+    cmds:
+      - |
+        gum confirm "Do you want to execute base cluster setup on {{ .CLUSTER_NAME }}?" || exit 0
+
+        machineshop render \
+        --source local \
+        --template {{ .PATH_CLUSTER_TEMPLATE }} \
+        --output file \
+        --kind multikey \
+        --key kind-infra \
+        --destination {{ .CLUSTER_INFRA_HELMFILE }} \
+        --values "source={{ .USER_WORKING_DIR }},clusterName={{ .CLUSTER_NAME }}"
+
+        START_TIME=$(date +%s)
+        TIMEOUT=180 # seconds
+
+        while true; do
+
+          echo "RUNNING HELMFILE APPLY..."
+          helmfile apply -f {{ .CLUSTER_INFRA_HELMFILE }} --kubeconfig {{ .PATH_KUBE_CONFIG }} && \
+          echo "RUNNING HELMFILE SYNC..." && \
+          helmfile sync -f {{ .CLUSTER_INFRA_HELMFILE }} --kubeconfig {{ .PATH_KUBE_CONFIG }} && \
+          { echo "Commands succeeded. Exiting loop."; break; }
+
+          CURRENT_TIME=$(date +%s)
+          ELAPSED=$(( CURRENT_TIME - START_TIME ))
+
+          if [ $ELAPSED -ge ${TIMEOUT} ]; then
+            echo "COMMANDS ARE STILL FAILING AFTER ONE MINUTE. EXITING WITH ERROR."
+            exit 1
+          fi
+
+          echo "RETRYING IN 5 SECONDS..."
+          sleep 5
+
+        done
+
+        kubectl get po -A --kubeconfig {{ .PATH_KUBE_CONFIG }}
+
+  destroy-kind-cluster:
+    desc: Destroy kind cluster
+    env:
+      KUBECONFIG: "{{ .PATH_KUBE_CONFIG }}"
+    cmds:
+      - |
+        if kind get clusters | grep -wq "{{ .CLUSTER_NAME }}"; then
+
+          kubectl get nodes -o wide --kubeconfig {{ .PATH_KUBE_CONFIG }}
+
+          # DELETE EXISTING CLUSTER
+          gum confirm "Do you want to destroy existing cluster {{ .CLUSTER_NAME }} and rebuild it?" || exit 0
+          echo "Cluster '{{ .CLUSTER_NAME }}' exists (already). Deleting it..."
+          kind delete clusters "{{ .CLUSTER_NAME }}"
+
+        fi
+
+  create-kind-cluster:
+    desc: Create, Start & Configure kind cluster
+    env:
+      KUBECONFIG: "{{ .PATH_KUBE_CONFIG }}"
+    cmds:
+      - task: destroy-kind-cluster
+      # - |
+      #   if kind get clusters | grep -wq "{{ .CLUSTER_NAME }}"; then
+
+      #     kubectl get nodes
+
+      #     # DELETE EXISTING CLUSTER
+      #     gum confirm "Do you want to destroy existing cluster {{ .CLUSTER_NAME }} and rebuild it?" || exit 0
+      #     echo "Cluster '{{ .CLUSTER_NAME }}' exists (already). Deleting it..."
+      #     kind delete clusters "{{ .CLUSTER_NAME }}"
+
+      #   fi
+      - |
+        cat {{ .KIND_CONFIG_PATH }}
+        gum confirm "Do you want to create cluster {{ .CLUSTER_NAME }}?" || exit 0
+
+        # CREATE NEW CLUSTER
+        machineshop render \
+        --source local \
+        --template {{ .PATH_CLUSTER_TEMPLATE }} \
         --output file \
         --values "clusterName={{ .CLUSTER_NAME }}" \
         --kind multikey \
         --key kind \
         --destination {{ .KIND_CONFIG_PATH }}
 
+        kind create cluster --config {{ .KIND_CONFIG_PATH }} --name {{ .CLUSTER_NAME }} --kubeconfig {{ .PATH_KUBE_CONFIG }}
+        kubectl get nodes
+
+      - task: execute-base-cluster-setup
+      - task: output-ingress-nipio
+
+  output-ingress-nipio:
+    desc: Output ingress domain
+    env:
+      KUBECONFIG: "{{ .PATH_KUBE_CONFIG }}"
+    cmds:
       - |
-        if kind get clusters | grep -wq "{{ .CLUSTER_NAME }}"; then
-          echo "Cluster '{{ .CLUSTER_NAME }}' exists (already). Deleting it..."
-          kind delete clusters "{{ .CLUSTER_NAME }}"
-        fi
+        echo *.$(kubectl get nodes -o json | jq -r '.items[] | select(.metadata.labels."ingress-ready" == "true") | .status.addresses[] | select(.type == "InternalIP") | .address').nip.io
 
-      - |
-        kind create cluster --config {{ .KIND_CONFIG_PATH }} --name {{ .CLUSTER_NAME }} --kubeconfig {{ .PATH_KUBECONFIG }}
-        kubectl get nodes --kubeconfig ~/.kube/kind-{{ .CLUSTER_NAME }}
-
-      - |
-        machineshop render \
-        --source local \
-        --template {{ .DEV_CLUSTER }} \
-        --output file \
-        --kind multikey \
-        --key kind-infra \
-        --destination {{ .KIND_INFRA_HELMFILE }} \
-        --values "source={{ .USER_WORKING_DIR }}"
-
-      - |
-        #!/usr/bin/env bash
-        start_time=$(date +%s)
-        timeout=120  # seconds
-        export KUBECONFIG={{ .PATH_KUBECONFIG }}
-
-        while true; do
-          echo "RUNNING HELMFILE APPLY..."
-          helmfile apply -f {{ .KIND_INFRA_HELMFILE }} && \
-          echo "RUNNING HELMFILE SYNC..." && \
-          helmfile sync -f {{ .KIND_INFRA_HELMFILE }} && \
-          { echo "Commands succeeded. Exiting loop."; break; }
-
-          current_time=$(date +%s)
-          elapsed=$(( current_time - start_time ))
-          if [ $elapsed -ge $timeout ]; then
-            echo "COMMANDS ARE STILL FAILING AFTER ONE MINUTE. EXITING WITH ERROR."
-            exit 1
-          fi
-          echo "RETRYING IN 5 SECONDS..."
-          sleep 5
-        done
-
-      - |
-        export KUBECONFIG={{ .PATH_KUBECONFIG }}
-        kubectl get nodes && kubectl get po -A
-    vars:
-      CLUSTER_NAME: helm-dev
-      PATH_KUBECONFIG: ~/.kube/kind-{{ .CLUSTER_NAME }}
-      INFRA_HELMFILES: "{{ .DEV_CLUSTER_DIR }}/{{ .CLUSTER_NAME }}-kind-infra.yaml"
-      KIND_CLUSTER_CONFIG: "{{ .DEV_CLUSTER_DIR }}/{{ .CLUSTER_NAME }}.yaml"
+  check:
+    desc: "Run pre-commit hooks"
+    cmds:
+      - pre-commit run -a
 
   k3d:
     desc: Create, Start & Configure k3d cluster
@@ -179,48 +280,7 @@ tasks:
         branch=$(printf "%s\n" "${branches[@]}" | gum choose)
         git checkout ${branch} && git pull
 
-  create-test-release:
-    desc: Switch to local branch
-    cmds:
-      - rm -rf {{ .TEST_DIR }}/* && mkdir {{ .TEST_DIR }} || true
-      - |
-        release=$(yq '.template | keys | .[]' {{ .TEST_RELEASE_TEMPLATES }} | gum choose)
-        folder=$(find {{ .SEARCH_FOLDERS }} -type f -name "${release}.yaml" -exec dirname {} \; | sort -u)
-        domain=$(hostname).$(kubectl get nodes -o json | jq -r '.items[] | select(.metadata.labels."ingress-ready" == "true") | .status.addresses[] | select(.type == "InternalIP") | .address').nip.io
 
-        machineshop render \
-        --source local \
-        --template {{ .TEST_RELEASE_TEMPLATES }} \
-        --output file \
-        --kind multikey \
-        --key ${release} \
-        --destination {{ .TEST_DIR }}/${release}.yaml \
-        --values "source={{ .USER_WORKING_DIR }}/${folder}/${release}.yaml, domain=${domain}"
-
-        helmfile template -f {{ .TEST_DIR }}/${release}.yaml
-
-        SELECTED_KUBECONFIG=$(gum choose {{ .ALL_KUBECONFIGS }})
-        echo SWITCHING TO ${SELECTED_KUBECONFIG//\"/}
-        printf "\n\nexport KUBECONFIG={{ .KUBECONFIG_FOLDER }}/${SELECTED_KUBECONFIG//\"/}\n\n"
-
-        export KUBECONFIG={{ .KUBECONFIG_FOLDER }}/${SELECTED_KUBECONFIG//\"/}
-        kubectl get nodes
-
-        gum confirm "Do you want to apply ${release}?" || exit 0
-
-        echo "Apply: helmfile apply -f {{ .TEST_DIR }}/${release}.yaml"
-        helmfile apply -f {{ .TEST_DIR }}/${release}.yaml
-        code {{ .TEST_DIR }}/${release}.yaml
-        sleep 10 && kubectl get po -A
-
-        gum confirm "Do you want to destroy ${release}?" || exit 0
-        helmfile destroy -f {{ .TEST_DIR }}/${release}.yaml
-        sleep 10 && kubectl get po -A
-    vars:
-      KUBECONFIG_FOLDER: ~/.kube
-      SEARCH_FOLDERS: "infra apps database"
-      ALL_KUBECONFIGS:
-        sh: ls {{ .KUBECONFIG_FOLDER }} | xargs -n1 printf '"%s" '
 
   uninstall-release:
     desc: Uninstall release
@@ -250,6 +310,8 @@ tasks:
           echo "Creating: ${release} include"
 
             folder=$(find {{ .SEARCH_FOLDERS }} -type f -name "${release}.yaml" -exec dirname {} \; | sort -u)
+            clusterIssuer=$(kubectl get clusterissuer -o jsonpath='{.items[0].metadata.name}')
+            storageClass=standard
 
             machineshop render \
             --source local \
@@ -294,11 +356,6 @@ tasks:
         git push origin ${BRANCH_NAME}
       - git branch
       - git branch --set-upstream-to=origin/main ${BRANCH_NAME}
-
-  check:
-    desc: "Run pre-commit hooks"
-    cmds:
-      - pre-commit run -a
 
   run-pre-commit-hook:
     deps:
